core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG

from .settings import base
from django.contrib.staticfiles.urls import static

admin.site.site_header = base.SITE_NAME+'管理サイト'
admin.site.site_title = base.SITE_NAME+'管理サイト'

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('course/', include('course.urls')),
  path('chapter/', include('chapter.urls')),
  path('exam/', include('exam.urls')),
  path('lesson/', include('lesson.urls')),
  path('query/', include('query.urls')),
  path('notification/', include('notification.urls')),
  path('situation/', include('situation.urls')),
  path('', include('home.urls')),
  path('', include('user_sessions.urls', 'user_sessions')),
]
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if DEBUG:
  import debug_toolbar
  urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

notification/urls.py
from django.urls import path
from .views import Index, Detail

app_name = 'notification'

urlpatterns = [
  path('', Index.as_view(), name='index'),
  path('detail/<int:pk>', Detail.as_view(), name='detail'),

]

notification/models.py
from django.db import models
from accounts.models import CustomUser
from simple_history.models import HistoricalRecords
from django.utils import timezone

# Create your models here.


class ElmsNotification(models.Model):
  TARGET_CHOICE = (
    (1, 'ログイン前のトップに公開'),
    (0, 'ログイン後表示'),
  )
  target = models.IntegerField(verbose_name='お知らせ掲載場所', choices=TARGET_CHOICE, blank=True, null=True)
  title = models.CharField(verbose_name='お知らせ題', max_length=200)
  content = models.TextField(verbose_name='お知らせ内容', )
  created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
  modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
  deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
  history = HistoricalRecords()

  def __str__(self):
    return self.title

  class Meta:
    db_table = 'elms_notification'
    verbose_name = 'お知らせ情報'
    verbose_name_plural = 'お知らせ情報'

notification/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import ElmsNotification
from core.utilities import getNotifications


class Index(LoginRequiredMixin, ListView):
  model = ElmsNotification
  queryset = ElmsNotification.objects.filter(deleted__isnull=True, target=0).order_by('-id').all()
  template_name = 'notification/index.html'


class Detail(LoginRequiredMixin, DetailView):
  def get(self, request, *args, **kwargs):
    context = {}
    context['detail']         = ElmsNotification.objects.filter(deleted__isnull=True, id=self.kwargs['pk']).first()
    context['notifications'] = getNotifications()
    return render(request, 'notification/detail.html', context)

templates/notification/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | お知らせ一覧{% endblock %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ detail.title }}</h5>
<p class="text-muted mb-0 text-end">{{ detail.created|date:'Y-m-d H:i:s' }}</p>
<p>{{ detail.content|linebreaks }}</p>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/notification/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | お知らせ一覧{% endblock %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ SITE_NAME }} お知らせ</h5>
{% for record in object_list %}
  <div class="row">
    <div class="col-3"><p>{{ record.created|date:'Y-m-d H:i:s' }}</p></div>
    <div class="col"><p><a href="{% url 'notification:detail' record.pk %}" class="text-start text-decoration-none">{{ record.title|truncatechars:'30' }}</a></p></div>
  </div>
{% endfor %}
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}