core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG

from .settings import base
from django.contrib.staticfiles.urls import static

admin.site.site_header = base.SITE_NAME+'管理サイト'
admin.site.site_title = base.SITE_NAME+'管理サイト'

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('course/', include('course.urls')),
  path('chapter/', include('chapter.urls')),
  path('exam/', include('exam.urls')),
  path('lesson/', include('lesson.urls')),
  path('query/', include('query.urls')),
  path('notification/', include('notification.urls')),
  path('situation/', include('situation.urls')),
  path('', include('home.urls')),
  path('', include('user_sessions.urls', 'user_sessions')),
]
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if DEBUG:
  import debug_toolbar
  urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

exam/urls.py
from django.urls import path
from .views import Index, CorrectView

app_name = 'exam'


urlpatterns = [
  path('<int:chapter_id>', Index.as_view(), name='index'),
  path('correct/<int:chapter_id>', CorrectView.as_view(), name='correct'),
]

exam/models.py
from django.db import models
from chapter.models import ElmsChapter
from accounts.models import CustomUser
import re
from simple_history.models import HistoricalRecords

# Create your models here.
class ElmsExam(models.Model):
  question_type = models.CharField(verbose_name='種類', max_length=20)
  title = models.CharField(verbose_name='タイトル', max_length=200)
  body = models.CharField(verbose_name='試験内容', max_length=200)
  options = models.TextField(verbose_name='回答', blank=True, null=True)
  correct = models.IntegerField(verbose_name='正解', )
  score = models.IntegerField(verbose_name='点数', )
  explain = models.TextField(verbose_name='説明', blank=True, null=True)
  comment = models.TextField(verbose_name='備考', blank=True, null=True)
  created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
  modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
  deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
  elms_exam_chapter = models.ForeignKey(ElmsChapter, on_delete=models.CASCADE, related_name='exam_chapter', verbose_name='章・単元', )
  elms_exam_user = models.ManyToManyField(CustomUser, through='ExamUserShip')
  history = HistoricalRecords()

  def __str__(self):
    return self.title

  class Meta:
    db_table = 'elms_exam'
    verbose_name = '試験情報'
    verbose_name_plural = '試験情報'


class ExamUserShip(models.Model):
  exam = models.ForeignKey(ElmsExam, on_delete=models.CASCADE, verbose_name='試験',)
  custom_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='受験者', )
  answer = models.IntegerField(blank=True, null=True, verbose_name='回答',)
  chapter_id = models.IntegerField(blank=True, null=True)
  is_right = models.BooleanField(default=False, verbose_name='判定',)
  score = models.IntegerField(default=0, verbose_name='点数',)
  created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
  modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
  deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
  history = HistoricalRecords()

  def __str__(self):
    reg_obj = re.compile(r"<[^>]*?>")
    return reg_obj.sub('', self.exam.body)

  class Meta:
    db_table = 'elms_exam_user_ship'
    verbose_name = '受験者と成績'
    verbose_name_plural = '受験者と成績'

exam/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from .models import ElmsExam, ExamUserShip
from chapter.models import ElmsChapter, ElmsChapterUserShip
from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils import timezone
from core.utilities import getNotifications

# Create your views here.
class Index(LoginRequiredMixin, ListView):
  template_name = 'exam/index.html'
  model = ElmsExam

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['examinations'] = ElmsExam.objects.filter(deleted__isnull=True, elms_exam_chapter=self.kwargs['chapter_id'])
    context['exam_first'] = ElmsExam.objects.filter(deleted__isnull=True, elms_exam_chapter=self.kwargs['chapter_id']).first()
    context['exam_last'] = ElmsExam.objects.filter(deleted__isnull=True, elms_exam_chapter=self.kwargs['chapter_id']).last()
    context['chapter'] = ElmsChapter.objects.filter(deleted__isnull=True, id=self.kwargs['chapter_id']).first()
    context['notifications'] = getNotifications()

    return context


class CorrectView(LoginRequiredMixin, CreateView):
  template_name = 'exam/result.html'
  model = ExamUserShip
  fields = ("exam", "custom_user", "answer", "is_right", "chapter_id", "score")

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    if not ExamUserShip.objects.filter(deleted__isnull=True, custom_user=self.request.user.pk, chapter_id=self.kwargs['chapter_id']).exists():
      total_score=total_correct=cnt=0
      correct_rate=''
      for i in range(int(self.request.POST.get("first")), int(self.request.POST.get("last"))+1):
        post_exam = "exam" + str(i)
        #解答と正解が一致した場合、is_rightをtrueにし、scoreをexam.scoreで上書き
        exam_rs_right = False
        exam_rs_score = 0
        exam_rs = ElmsExam.objects.filter(deleted__isnull=True, pk=i, correct=self.request.POST.get(post_exam)).first()
        if exam_rs:
          exam_rs_right=True
          exam_rs_score=exam_rs.score
          total_correct+=1
        ExamUserShip.objects.create(
          exam_id=i,
          custom_user_id=self.request.user.pk,
          answer=self.request.POST.get(post_exam),
          is_right=exam_rs_right,
          score=exam_rs_score,
          chapter_id=self.kwargs['chapter_id'],
        )
        total_score+=exam_rs_score
        cnt+=1
        correct_rate=str(total_correct)+"/"+str(cnt)
      chapter = ElmsChapter.objects.filter(deleted__isnull=True, id=self.kwargs['chapter_id']).first()
      elms_chapter_user = ElmsChapterUserShip.objects.filter(deleted__isnull=True, chapter_id=self.kwargs['chapter_id'], custom_user=self.request.user.pk).first()
      chapter_user_ship = ElmsChapterUserShip.objects.get(pk=elms_chapter_user.id)
      chapter_user_ship.total_score = total_score
      chapter_user_ship.correct_rate = correct_rate
      chapter_user_ship.modified = timezone.now()
      chapter_user_ship.save()

    context['chapter'] = ElmsChapter.objects.filter(deleted__isnull=True, id=self.kwargs['chapter_id']).first()
    context['results'] = ExamUserShip.objects.filter(deleted__isnull=True, custom_user=self.request.user.pk, chapter_id=self.kwargs['chapter_id']).select_related()
    context['notifications'] = getNotifications()
    return context

templates/exam/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load utility %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | 理解度問題{% endblock %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ chapter.chapter_title }} 理解問題</h5>

<form action="{% url 'exam:correct' chapter.pk %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="first" value="{{ exam_first.id }}">
  <input type="hidden" name="last" value="{{ exam_last.id }}">
  <ol>
    {% for exam in examinations %}
      <li>{{ exam.body|safe }}</li>
      <ul class="mb-5">
        {% for opt in exam.options|split:'|' %}
          <li class="list-unstyled mb-2">
            <div class="form-check">
              <input type="radio" name="exam{{ exam.id }}" value="{{ forloop.counter }}" id="exam{{ exam.id }}{{ forloop.counter }}">
              <label class="form-check-label" for="exam{{ exam.id }}{{ forloop.counter }}"> {{ opt }}</label>
            </div>
          </li>
        {%  endfor %}
      </ul>
    {%  endfor %}
  </ol>
  <div class="row">
    <div class="col"> <input type="submit" class="btn btn-outline-success w-50" value="解答する"></div>
  </div>
</form>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/exam/result.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load utility %}
{% block bootstrap5_extra_head %}{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | 理解度問題 結果{% endblock %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ chapter.chapter_title }} 理解度問題 結果</h5>
{% for result in results.all %}
  <h6 class="mi-m">{{ result.exam.body }}</h6>
  <div class="row mb-3">
    <div class="col">正解</div>
    <div class="col">貴方の解答</div>
  </div>
  <div class="row mb-3">
    <div class="col">
      {% for opt in result.exam.options|split:'|' %}
      <p>
        {% if result.exam.correct == forloop.counter %}
          <b><i class="bi bi-circle"></i>{{ opt }}</b>
        {% else %}
          <i class="bi bi-x"></i>{{ opt }}
        {% endif %}
      </p>
      {%  endfor %}
    </div>
    <div class="col">
      {% for opt in result.exam.options|split:'|' %}
        {% if result.answer == forloop.counter %}
          {% if result.exam.correct == forloop.counter %}<i class="bi bi-circle"></i>{% else %}<i class="bi bi-x"></i>{% endif %}{{ opt }}
        {% endif %}
      {%  endfor %}
    </div>
  </div>
{% endfor %}
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}