accounts/urls.py
from django.urls import path
from accounts.views import Signin, Signout, PasswordModify, PasswordModifiedView, ProfileDetail, UserUpdate
from . import views

app_name = 'accounts'

urlpatterns=[
  path('signin/', Signin.as_view(), name='signin'),
  path('signout/', Signout.as_view(),name='signout'),
  path('password_modify/', PasswordModify.as_view(), name='password_modify'),
  path('password_modified/', PasswordModifiedView.as_view(), name='password_modified'),
  path('profile/', ProfileDetail.as_view(), name='profile_detail'),
  path('profile/<int:pk>/edit', UserUpdate.as_view(), name='profile_edit'),
  path('media/', views.MediaView.as_view(), name='media'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG

from .settings import base
from django.contrib.staticfiles.urls import static

admin.site.site_header = base.SITE_NAME+'管理サイト'
admin.site.site_title = base.SITE_NAME+'管理サイト'

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('course/', include('course.urls')),
  path('chapter/', include('chapter.urls')),
  path('exam/', include('exam.urls')),
  path('lesson/', include('lesson.urls')),
  path('query/', include('query.urls')),
  path('notification/', include('notification.urls')),
  path('situation/', include('situation.urls')),
  path('', include('home.urls')),
  path('', include('user_sessions.urls', 'user_sessions')),
]
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if DEBUG:
  import debug_toolbar
  urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

home/urls.py
from django.urls import path
from home.views import HomeIndexView, OverviewView

app_name = 'home'

urlpatterns = [
    path('', HomeIndexView.as_view(), name='index'),
    path('overview/', OverviewView.as_view(), name='overview'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
import hashlib
from simple_history.models import HistoricalRecords


class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, username, email, password, **extra_fields):
		if not email:
			raise ValueError('Emailを入力して下さい')
		email = self.normalize_email(email)
		username = self.model.normalize_username(username)
		user = self.model(username=username, email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self.db)
		return user

	def create_user(self, username, email, password=None, **extra_fields):
		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, username, email, password, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		if extra_fields.get('is_staff') is not True:
			raise ValueError('is_staff=Trueである必要があります。')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('is_superuser=Trueである必要があります。')
		return self._create_user(username, email, password, **extra_fields)


def avater_file_path(instance, filename):
  hash = hashlib.sha256(str(instance.id).encode()).hexdigest()
  return f'images/icons/{hash}/{filename}'

class CustomUser(AbstractBaseUser, PermissionsMixin):
	username_validator = UnicodeUsernameValidator()

	username = models.CharField(_("username"), max_length=50, validators=[username_validator], blank=True)
	mobile = models.CharField(_("携帯"), max_length=20, blank=True)
	first_name = models.CharField(_("名"), max_length=50, blank=True)
	last_name = models.CharField(_("姓"), max_length=50, blank=True)
	email = models.EmailField(_("メール"), unique=True)
	company = models.CharField(_("会社名"), max_length=100, blank=True)
	department = models.CharField(_("所属"), max_length=100, blank=True)
	position = models.CharField(_("役職"), max_length=100, blank=True)
	occupation = models.CharField(_("職種"), max_length=100, blank=True)
	avater = models.ImageField(upload_to=avater_file_path)


	#prefecture = models.CharField(_("住所（都道府県）"), max_length=50, blank=True)
	#postcode = models.CharField(_("郵便番号"), max_length=10, blank=True)
	#city = models.CharField(_("住所（市区）"), max_length=50, blank=True)
	#locality = models.CharField(_("住所（町村）"), max_length=50, blank=True)
	#block = models.CharField(_("住所（番地）"), max_length=50, blank=True)
	#building = models.CharField(_("住所（建物名・部屋番号）"), max_length=100, blank=True)

	is_staff = models.BooleanField(_("staff status"), default=False)
	is_active = models.BooleanField(_("active"), default=True)
	date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
	created = models.DateTimeField(verbose_name='生成日時', auto_now_add=True)
	modified = models.DateTimeField(verbose_name='更新日時', auto_now=True)
	deleted = models.DateTimeField(verbose_name='削除日時', blank=True, null=True)
	delete_memo = models.TextField(verbose_name='削除理由', blank=True, null=True)
	history = HistoricalRecords()

	objects = UserManager()
	USERNAME_FIELD = "email"
	EMAIL_FIELD = "email"
	REQUIRED_FIELDS = ['username']

	class Meta:
		verbose_name = _("user")
		verbose_name_plural = _("users")

	def clean(self):
		super().clean()
		self.email = self.__class__.objects.normalize_email(self.email)

	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, get_user_model
from django.utils.text import capfirst
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()

class EmailAuthenticationForm(forms.Form):
  email = forms.EmailField(label=_("Email"), max_length=254, widget=forms.TextInput(attrs={'autofocus': True}))
  password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput)
  error_messages = {
      'invalid_login': "メールアドレスまたはパスワードに誤りがあります",
      'inactive': _("This account is inactive"),
  }

  def __init__(self, request=None, *args, **kwargs):
    self.request = request
    self.user_cache = None
    super().__init__(*args, **kwargs)
    self.email_field = UserModel._meta.get_field("email")
    if self.fields["email"].label is None:
      self.fields["email"].label = capfirst(self.email_field.verbose_name)

  def clean(self):
    email = self.cleaned_data.get("email")
    password = self.cleaned_data.get("password")
    if email is not None and password:
      self.user_cache = authenticate(self.request, email=email, password=password)
      if self.user_cache is None:
        raise forms.ValidationError(
          self.error_messages['invalid_login'],
          code='invalid_login',
          params={"email": self.email_field.verbose_name}
        )
      else:
        self.confirm_login_allowed(self.user_cache)
      return self.cleaned_data

  def confirm_login_allowed(self, user):
      if not user.is_active:
        raise forms.ValidationError(self.error_messages["inactive"], code='inactive')

  def get_user_id(self):
      if self.user_cache:
        return self.user_cache.id
      return None

  def get_user(self):
      return self.user_cache

class PasswordModifyForm(PasswordChangeForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

class ProfileUpdateForm(forms.ModelForm):
  """ユーザー情報更新フォーム"""

  class Meta:
    model = UserModel
    fields = ('last_name', 'first_name', 'username', 'mobile', 'email', 'company', 'department', 'position', 'occupation', 'avater')
    labels = {
      'first_name' : '名前',
      'last_name'  : '苗字',
      'username'   : 'ユーザー名',
      'mobile'     : '携帯電話',
      'email'      : 'メールアドレス',
      'company'    : '会社',
      'department' : '所属',
      'position'   : '役職',
      'occupation' : '職種',
      'avater'     : 'プロフィール画像',
    }

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render, resolve_url
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import reverse_lazy
from .forms import EmailAuthenticationForm, PasswordModifyForm
from django.views.generic import FormView, DetailView, TemplateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
from .forms import ProfileUpdateForm
from core.settings import base
from PIL import Image
import io
from django.http import HttpResponse
from core.utilities import getNotifications

from lesson.models import ElmsLesson, ElmsLessonUserShip
CustomUser = get_user_model()


class Signin(LoginView):
  form_class = EmailAuthenticationForm
  template_name = 'accounts/signin.html'


class Signout(LogoutView):
  template_name = 'accounts/signout.html'


class PasswordModify(PasswordChangeView):
  """パスワード変更ビュー"""
  form_class = PasswordModifyForm
  success_url = reverse_lazy('accounts:password_modified')
  template_name = 'accounts/password_modify.html'
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['notifications'] = getNotifications()
    return context


class PasswordModifiedView(PasswordChangeDoneView):
  template_name = 'accounts/password_modified.html'
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['notifications'] = getNotifications()
    return context


class ProfileDetail(LoginRequiredMixin, TemplateView):
  model = CustomUser
  template_name = 'accounts/profile.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['notifications'] = getNotifications()
    return context

class UserUpdate(LoginRequiredMixin, UpdateView):
  model = CustomUser
  form_class = ProfileUpdateForm
  template_name = 'accounts/profile_edit.html'
  success_url = reverse_lazy('accounts:profile_detail')

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['notifications'] = getNotifications()
    return context


class MediaView(LoginRequiredMixin, View):
  """ 画像取得 のビュー """
  def get(self, request, *args, **kwargs):
    img_path = CustomUser.objects.filter(deleted__isnull=True, id=self.request.user.pk).first()
    img = Image.open(base.MEDIA_ROOT+'/'+str(img_path.avater))
    imgByteArr = io.BytesIO()
    img.save(imgByteArr, format=img.format)
    imgByteArr = imgByteArr.getvalue()

    response = HttpResponse(imgByteArr, status=200)
    response["Content-Type"] = "image/jpeg"
    response["Content-Disposition"] = "inline; filename={0}".format(img)
    return response

templates/accounts/password_modified.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block bootstrap5_title %}{{ SITE_NAME }} | パスワード変更終了{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<main>
  <p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:signin' %}">ログイン</a>
  </p>
</main>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/accounts/password_modify.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block bootstrap5_title %}{{ SITE_NAME }} | パスワード変更{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<main>
  <form action="" method="POST">
  {{ form.non_field_errors }}
    {% bootstrap_form form %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">変更する</button>
  </form>
</main>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block bootstrap5_title %}{{ SITE_NAME }} | プロフィール{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ SITE_NAME }} プロフィール</h5>
<div class="row">
  <div class="col-lg-4">
    <div class="card mb-4">
      <div class="card-body text-center">
        <img src="{% url 'accounts:media' %}" width="128px" height="128px">
        <h5 class="my-3">{{ user.username }}</h5>
        <p class="text-muted mb-1">{{ user.occupation }}</p>
        <p class="text-muted mb-4">{{ user.company }}{{ user.department }}</p>
        <div class="d-flex justify-content-center mb-2">
          <a href="{% url 'accounts:profile_edit' user.pk %}" button type="button" class="btn btn-primary w-100">プロフィール編集</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">ユーザー名</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.username }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">名前</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.last_name }}　{{ user.first_name }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">Email</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.email }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">Mobile</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.mobile }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">組織</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.company }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">部門・部署</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.department }}</p></div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3"><p class="mb-0">役職・職種</p></div>
          <div class="col-sm-9"><p class="text-muted mb-0">{{ user.position }}{{ user.occupation }}</p></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/accounts/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block bootstrap5_title %}{{ SITE_NAME }} | プロフィール編集 {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<h5 class="pb-4 mb-4 fst border-bottom">{{ SITE_NAME }} プロフィール編集</h5>
<div class="row">
  <div class="col-lg-4">
    <div class="card mb-4">
      <div class="card-body text-center">
        <img src="/media/{{ user.avater }}" width="128px" height="128px">
        <h5 class="my-3">{{ user.username }}</h5>
        <p class="text-muted mb-1">{{ user.occupation }}</p>
        <p class="text-muted mb-4">{{ user.company }}{{ user.department }}</p>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="card mb-4">
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {{ form.non_field_errors }}
          {% bootstrap_form form %}
          <p><img src="{% url 'accounts:media' %}" width="128px" height="128px"></p>
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg w-50">更新する</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/accounts/signin.html
{% extends "base_sign.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block bootstrap5_extra_head %}
  <link rel="stylesheet" src="signin.css">
{% endblock %}
{% block bootstrap5_title %}{{ SITE_NAME }} | サインイン{% endblock %}
{% block content %}
<div class="col-lg-6 mx-auto p-3 py-md-5">
  <h3 class="pb-4 mb-4 fst border-bottom mi-l"><i class="fa-solid fa-user-lock"></i>{{ SITE_NAME }} サインイン</h3>
  <main>
    <form method="post">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}" />
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="サインインする" %}
    </form>
  </main>
  {% include 'footer.html' %}
</div>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}

templates/accounts/signout.html
{% extends "base_sign.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block bootstrap5_title %}{{ SITE_NAME }} | パスワード変更終了{% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<main>
  <div class="row justify-content-center">
    <div class="col-lg-5">
      <h3 class="pb-4 mb-4 fst border-bottom mi-l"><i class="fa-solid fa-user-lock"></i>{{ SITE_NAME }} パスワード変更終了</h3>
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header">
          <h3 class="text-center font-weight-light my-4">サインアウト</h3></div>
        <div class="card-body">
          <p>サインアウトしました。</p>
          <p>ご利用ありがとうございました。</p>
          <hr class='mt-2 mb-2'>
          <p><a href="{% url 'accounts:signin' %}">もう一度サインインする</a></p>
          <p><a href="{% url 'home:index' %}">Topに戻る</a></p>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}