accounts/urls.py
from django.urls import path
from accounts.views import Signin, Signout, PasswordModify, PasswordModifiedView, ProfileDetail, UserUpdate
from . import views

app_name = 'accounts'

urlpatterns=[
  path('signin/', Signin.as_view(), name='signin'),
  path('signout/', Signout.as_view(),name='signout'),
  path('password_modify/', PasswordModify.as_view(), name='password_modify'),
  path('password_modified/', PasswordModifiedView.as_view(), name='password_modified'),
  path('profile/', ProfileDetail.as_view(), name='profile_detail'),
  path('profile/<int:pk>/edit', UserUpdate.as_view(), name='profile_edit'),
  path('media/', views.MediaView.as_view(), name='media'),
]

chapter/urls.py
from django.urls import path
from .views import Index

app_name = 'chapter'

urlpatterns = [
    path('', Index.as_view(), name='index'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings.base import DEBUG

from .settings import base
from django.contrib.staticfiles.urls import static

admin.site.site_header = base.SITE_NAME+'管理サイト'
admin.site.site_title = base.SITE_NAME+'管理サイト'

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('accounts.urls')),
  path('course/', include('course.urls')),
  path('chapter/', include('chapter.urls')),
  path('exam/', include('exam.urls')),
  path('lesson/', include('lesson.urls')),
  path('query/', include('query.urls')),
  path('notification/', include('notification.urls')),
  path('situation/', include('situation.urls')),
  path('', include('home.urls')),
  path('', include('user_sessions.urls', 'user_sessions')),
]
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

if DEBUG:
  import debug_toolbar
  urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

home/urls.py
from django.urls import path
from home.views import HomeIndexView, OverviewView

app_name = 'home'

urlpatterns = [
    path('', HomeIndexView.as_view(), name='index'),
    path('overview/', OverviewView.as_view(), name='overview'),
]

query/urls.py
from django.urls import path
from .views import IndexView, CommitView

app_name = 'query'

urlpatterns = [
  path('', IndexView.as_view(), name='index'),
  path('commit/', CommitView.as_view(), name='commit'),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block bootstrap5_title %}{{ SITE_NAME }}{% endblock %}</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <style>
    body {
      font-family: 'Noto Sans JP', sans-serif;
    }
    .mi-l i {
      margin-right: 10px;
      font-size: 30px;
    }
    .mi-m i {
      margin-right: 10px;
      font-size: 22px;
    }
  </style>
  {% block bootstrap5_extra_head %}{% endblock %}
</head>
<body>
<div class="container mt-5">
  {% include 'header.html' %}
  <main>
  <div class="row g-5">
    <div class="col-md-8">
    {% block content %}{% endblock content %}
    </div>
    <div class="col-md-4">
      {% include 'right_sidebar.html' %}
    </div>
  </div>
  </main>
{% include 'footer.html' %}
</div>
</body>
{% block javascripts %}{% endblock javascripts %}
</html>

templates/base_sign.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block bootstrap5_title %}{{ SITE_NAME }}{% endblock %}</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <style>
    body {
      font-family: 'Noto Sans JP', sans-serif;
    }
    .mi-l i {
      margin-right: 10px;
      font-size: 30px;
    }
    .mi-m i {
      margin-right: 10px;
      font-size: 22px;
    }
  </style>
  {% block bootstrap5_extra_head %}{% endblock %}
</head>
<body>
<div class="container mt-5">
  <main>
  <div class="row g-5">
    <div class="col-md-12">
    {% block content %}{% endblock content %}
    </div>
  </div>
  </main>
</div>
</body>
{% block javascripts %}{% endblock javascripts %}
</html>

templates/footer.html
<footer class="pt-5 my-5 text-muted border-top">
  Created by TABATA, Hitoshi & More &middot; &copy; 2023
</footer>

templates/header.html
<header class="blog-header">
  <div class="row flex-nowrap align-items-center">
    <div class="col-8">
      <h2 class="fst mi-l mb-5"><i class="fa-solid fa-user-lock"></i>{{ SITE_NAME }}</h2>
    </div>
    <div class="col-4">
      <div class="dropdown px-5">
        <a class="" href="#" role="" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="{% url 'accounts:media' %}" style="width:64px;height:auto;">
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-versions">
          <li class="list-group-item"><a href="{% url 'accounts:profile_detail' %}" class="text-decoration-none dropdown-item" rel="noopener norefferrer">プロフィール</a></li>
          <li><hr class="dropdown-divider"></li>
          <li class="list-group-item"><a href="{% url 'accounts:password_modify' %}" class="text-decoration-none dropdown-item" rel="noopener norefferrer">パスワード変更</a></li>
          <li><hr class="dropdown-divider"></li>
          <li class="list-group-item"><a href="{% url 'accounts:signout' %}" class="text-decoration-none dropdown-item" rel="noopener norefferrer">サインアウト</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

templates/home_header.html
<div class="row border-bottom mb-5">
  <div class="col-7">
    <h1 class="pb-4 mi-l"><img src="/media/images/common/lmson.png"  style="width:48px;height:auto;"> {{ SITE_NAME }}</h1>
  </div>
  <div class="col-5">
    <ul class="nav justify-content-end h5">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:index' %}" class="text-decoration-none">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'query:index' %}" class="text-decoration-none">お問い合わせ</a>
      </li>
    </ul>
  </div>
</div>

templates/right_sidebar.html
{% load static %}
<div class="position-sticky" style="top: 2rem;">
  <div class="px-4 py-2">
    <p>{{ user.email }}</p>
    <h5 class="mi-m"><i class="fa-sharp fa-solid fa-chalkboard"></i>MyLMS</h5>
    <p class="ms-3"><a href="{% url 'situation:lesson_index' %}" class="text-decoration-none">受講確認</a></p>
    <p class="ms-3"><a href="{% url 'situation:examination_index' %}" class="text-decoration-none">受験確認</a></p>
  </div>
  <div class="px-4 py-2">
    <h5 class="mi-m"><i class="fa-solid fa-user-lock"></i>コンテンツ</h5>
    <p class="ms-3"><a href="{% url 'chapter:index' %}" class="text-decoration-none">カリキュラム</a></p>
  </div>
  <div class="px-4 py-2">
    <h5 class="mi-m"><i class="fa-regular fa-message"></i>お知らせ</h5>
    {% for notification in notifications %}
      <p class="ms-3"><a href="{% url 'notification:detail' notification.pk %}" class="text-decoration-none">{{ notification.title|truncatechars:'15' }}</a></p>
    {% endfor %}
  </div>
</div>